version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: ./database/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: blog
    command: bash -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/backend
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db


volumes:
  mysql_data: